posts:
  world_snow:
    name: "Snow Outpost"
    zone: "world;outpost_snow"
    data:
      time: 50
      done:
        - "[command-server] say Fire Outpost has been captured by %player_name%"
  world_fire:
    0:
      name: "Fire Outpost 0"
      zone: "world;outpost_fire-0"
      data:
        time: 10
        done:
          - "[message] You have captured %outpost_name%"
          - "[command-server] say Fire Outpost has been captured by %player_name%"
          - "[command-server] give %player_name% GOLDEN_APPLE 64"
    1:
      name: "Fire Outpost 1"
      zone: "world;outpost_fire-1"
      data:
        time: 20
        done:
          - "[message] You have captured %outpost_name%"
    2:
      name: "Fire Outpost 2"
      zone: "world;outpost_fire-2"
      data:
        time: 30
        done:
          - "[message] You have captured %outpost_name%"
