name: Outposts
main: com.sxtanna.mc.posts.Outposts

version: '1.0-SNAPSHOT'
website: "https://gh.sxtanna.com"
authors: ["Sxtanna"]

depend:
  - 'WorldGuard'
  - 'ShopGUIPlus'
  - 'Factions'
softdepend:
  - 'PlaceholderAPI'
  - 'MVdWPlaceholderAPI'

commands:
  outposts:
    aliases: ["posts"]
    permission: "outposts.command"
    description: "main outposts management command"
    usage: "/outposts [info {outpost_name}, list, toggle, reload]"

permissions:
  outposts.command.*:
    description: "Allows access to all outposts commands"
    children:
      outposts.command.info: true
      outposts.command.list: true
      outposts.command.toggle: true
      outposts.command.reload: true
  outposts.command.info:
    description: "Shows the current state of an outpost"
  outposts.command.list:
    description: "Shows a list of all loaded outposts"
  outposts.command.toggle:
    description: "Toggles the reception of outpost status announcements"
  outposts.command.reload:
    description: "Reloads outposts"