name: Outposts
main: com.sxtanna.mc.posts.Outposts

version: '1.0-SNAPSHOT'
website: "https://gh.sxtanna.com"
authors: ["Sxtanna"]

depend:
  - 'WorldGuard'
  - 'ShopGUIPlus'
  - 'Factions'
softdepend:
  - 'PlaceholderAPI'

commands:
  outposts:
    aliases: ["posts"]
    description: "main outposts management command"
    permission: "outposts.command"
    usage: "/outposts info, list, reload]"